### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by conky2** [think-dev/Finder#13]
Hi, I'm having trouble getting a sample of this up and running on an iOS simulator.  Is there an example you can provide?  Thanks!

**Comment by think-dev** [comment]
Hello conky2. I've uploaded a new branch called __ExampleProject__. You can download and test this project. I hope it solves your doubts. Do not hesitate to come back here if you still have problems.

**Comment by conky2** [comment]
I'm seeing the following build error when I try the ExampleProject branch.
![screen shot 2017-01-18 at 7 42 53 am](https://cloud.githubusercontent.com/assets/25021281/22064508/e459a38e-dd51-11e6-8dcb-a53bfee0877c.png)

**Comment by think-dev** [comment]
Maybe you've not run `carthage update` on your command line?

**Comment by conky2** [comment]
Thanks!.  That did the trick.

**Comment by think-dev** [comment]
Great! I hope you enjoy Finder

**Comment by think-dev** [comment]
Due to CI problems, I've moved the example to a separate repo. You can find it on:

https://github.com/think-dev/FinderExample
